### ISSUE TITLE
Error after update to V4.5.21

### ISSUE THREAD

**Issue by RonnyB74** [nephros/x10iii-cam-button#4]
Since the Sailfish update from 4.5.19 to 4.5.21, the button cannot be activated. It no longer asks for the password. The following error message is displayed in the journal:

`Error starting org.nephros.sailfish.x10iiicamera`

I deleted the app via chum and reinstalled it. Unfortunately, this did not help.

Ronny

**Comment by nephros** [comment]
Thanks for reporting.

Unfortunately I can not test this myself as my X10iii device is still on 4.4 and will remain there for some time still.

Can you confirm that the issue is still there after a reboot?

**Comment by RonnyB74** [comment]
Unfortunately yes.

**Comment by nephros** [comment]
> Unfortunately yes.

Thanks.

can you please do a

```
devel-su
systemctl restart org.nephros.sailfish.x10iiicamera.service
systemctl status -l --no-pager org.nephros.sailfish.x10iiicamera.service
```

and post the output here?

**Comment by nephros** [comment]
Others do not seem to have this problem (https://forum.sailfishos.org/t/toggle-xperia-10iii-cameras/15975/20?u=nephros). So maybe it's an isolated case.

**Comment by RonnyB74** [comment]
Here is the output:

`[root@Xperia10III defaultuser]# systemctl restart org.nephros.sailfish.x10iiicamera.service
[root@Xperia10III defaultuser]# systemctl status -l --no-pager org.nephros.sailfish.x10iiicamera.service
● org.nephros.sailfish.x10iiicamera.service - Xperia 10III Triple Camera Toggle
   Loaded: loaded (/usr/lib/systemd/system/org.nephros.sailfish.x10iiicamera.service; static; vendor preset: enabled)
   Active: active (exited) since Mon 2023-07-24 17:43:11 CEST; 10s ago
     Docs: https://docs.sailfishos.org/Support/Help_Articles/Camera/#multiple-cameras-of-xperia-10-iii
  Process: 19285 ExecStart=/bin/bash -c /usr/bin/sed -i 's/multiCameraEnable=.*$/multiCameraEnable=TRUE/' $CAMXFILE && /usr/bin/pkill -f $CAMPROVIDER (code=exited, status=0/SUCCESS)
 Main PID: 19285 (code=exited, status=0/SUCCESS)`

`Jul 24 17:43:11 Xperia10III systemd[1]: Starting Xperia 10III Triple Camera Toggle...
Jul 24 17:43:11 Xperia10III systemd[1]: Started Xperia 10III Triple Camera Toggle.`

Strangely enough, the restart activates the button. But it cannot be deactivated by clicking on it.

**Comment by nephros** [comment]
Something must be amiss with polkit.

I'm guessing maybe the update isn't complete.

If you have `zypper` installed, try:

    zypper ref
    zypper up

The output of the second one would be interesting.
If you try this, do NOT proceed with anything zypper suggests, just post the output.

**Comment by RonnyB74** [comment]
Thank you, we did it. Somehow, there were complications with old app versions from the warehouse. This must have prevented Chum from updating a lib. I wouldn't have thought of that on my own!
